name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  functions-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run Cloud Functions emulator tests
        run: npm run test:emulator

  flutter-tests:
    runs-on: ubuntu-latest
    needs: functions-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run Flutter tests
        run: flutter test

  build:
    runs-on: ubuntu-latest
    needs:
      - functions-tests
      - flutter-tests
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build Flutter web app
        run: flutter build web --release
      - name: Build Android release APK
        run: flutter build apk --release
      - name: Archive web build
        run: tar -czf web-build.tar.gz -C build web
      - name: Prepare APK artifact
        run: cp build/app/outputs/flutter-apk/app-release.apk restaurant-pos-release.apk
      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build.tar.gz
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: restaurant-pos-release.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: artifacts
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: artifacts
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload web build asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/web-build.tar.gz
          asset_name: web-build.tar.gz
          asset_content_type: application/gzip
      - name: Upload Android APK asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/restaurant-pos-release.apk
          asset_name: restaurant-pos-release.apk
          asset_content_type: application/vnd.android.package-archive