// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACaFY_X8ktUAvuVQPCW2KesZprmtEcznE',
    appId: '1:844325570814:web:0a969c8188ddc2d4213daf',
    messagingSenderId: '844325570814',
    projectId: 'fluke-qr01',
    authDomain: 'fluke-qr01.firebaseapp.com',
    storageBucket: 'fluke-qr01.firebasestorage.app',
    measurementId: 'G-TG46QFYLTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCujpeFd6yOhhMTX_rFC7cWhJEW9qyGy9g',
    appId: '1:844325570814:android:f5ad2fbce5cfd14d213daf',
    messagingSenderId: '844325570814',
    projectId: 'fluke-qr01',
    storageBucket: 'fluke-qr01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj5VZlxBeBfSE-uTlaPJWEFEgfe_qVllk',
    appId: '1:844325570814:ios:450834cfd0c2547a213daf',
    messagingSenderId: '844325570814',
    projectId: 'fluke-qr01',
    storageBucket: 'fluke-qr01.firebasestorage.app',
    iosBundleId: 'com.example.restaurantAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj5VZlxBeBfSE-uTlaPJWEFEgfe_qVllk',
    appId: '1:844325570814:ios:450834cfd0c2547a213daf',
    messagingSenderId: '844325570814',
    projectId: 'fluke-qr01',
    storageBucket: 'fluke-qr01.firebasestorage.app',
    iosBundleId: 'com.example.restaurantAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACaFY_X8ktUAvuVQPCW2KesZprmtEcznE',
    appId: '1:844325570814:web:0a969c8188ddc2d4213daf',
    messagingSenderId: '844325570814',
    projectId: 'fluke-qr01',
    authDomain: 'fluke-qr01.firebaseapp.com',
    storageBucket: 'fluke-qr01.firebasestorage.app',
    measurementId: 'G-TG46QFYLTC',
  );

}